name: News Aggregator

on:
  schedule:
    - cron: "0 0,8,16 * * *"  # Runs at 00:00, 08:00, and 16:00 UTC
  push:
    branches:
      - main

jobs:
  aggregate-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 feedparser

    - name: Run news aggregator
      run: python news_aggregator.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add news.json
        git commit -m "Update news $(date +'%Y-%m-%d %H:%M:%S')"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
